# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

displayName: macOS SQLite
vmImage: macOS-10.13
variables:
  BACKEND: sqlite
  SQLITE_DATABASE_URL: /tmp/test.db
setup:
  - bash: |
      brew update &&
      brew install sqlite
    displayName: Install sqlite

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.6.2'

- script: |
    gem install bundler
    bundle install --without development production --retry=3 --jobs=4
  displayName: 'bundle install --without development production'

- script: bundle exec rake
  displayName: 'bundle exec rake'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Ruby tests'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
